---
# tasks file for Ansible-Httpd-Role
tasks:
        - name: "Installing httpd package"
          package:
                  name: "httpd"
        - name: "Installing PHP Runtime"
          package:
                  name: "php"
                  state: present
        - name: "Copying HTML Website code to /var/www/html/"
          copy:
                  src: "{{ web_page_deploy }}"
                  dest: "/var/www/html/{{ web_page_deploy }}"
                  force: True
          notify: httpd_restart
        - name: "Starting HTTPD services and Enabling it permanently"
          service:
                  name: "httpd"
                  state: started
                  enabled: true
